services:
  ui:
    image: product-catalog-ui:2.0
    build:
      context: ./product-catalogue-angular-frontent
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: product-catalog-backend:1.0
    build:
      context: ./product-catalogue-springboot-backend
      dockerfile: Dockerfile
    ports:
      - "9192:9192"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product_catalog_100?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.1
    container_name: product_catalog_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_catalog_100
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s

volumes:
  mysql_data:
